[package]
name = "rhammer"
version = "0.2.0"
edition = "2021"
license = "MIT"

[dependencies]
eframe = { version = "0.36.2", default-features = false, features = ["default_fonts", "glow", "x11", "wayland"] }
glam = "0.33"
anyhow = "1"
logos = "0.16"
egui-snarl = { version = "0.12", default-features = false }
rfd = "0.15"

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 3
