[workspace]
members = [".", "crates/*"]

[workspace.dependencies]
anyhow = "1"
logos = "0.16"
glam = "0.33"

[package]
name = "rhammer"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
rhammer-kv = { path = "crates/kv" }
rhammer-config = { path = "crates/config" }
rhammer-formats = { path = "crates/formats" }
rhammer-assets = { path = "crates/assets" }
rhammer-core = { path = "crates/core" }
rhammer-compile = { path = "crates/compile" }
eframe = { version = "0.36.2", default-features = false, features = ["default_fonts", "glow", "x11", "wayland"] }
glam = { workspace = true }
anyhow = { workspace = true }
rfd = "0.15"

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 3
